-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 16:59:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sample
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portal` ;

-- -----------------------------------------------------
-- Schema sample
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portal` DEFAULT CHARACTER SET utf8 ;
USE `portal` ;

-- -----------------------------------------------------
-- Table `portal`.`cp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portal`.`list` ;

CREATE TABLE IF NOT EXISTS `portal`.`list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL COMMENT '名前',
  `image_url` VARCHAR(128) NOT NULL COMMENT '画像パス',
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
  `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日',
  `deleted_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '削除日',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'リスト'
PACK_KEYS = Default;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
